- hosts: localhost
  connection: localhost
  gather_facts: no
  vars_files:
  - cred.yml

  tasks:
  - name: Create a new Key-pair
    ec2_key:
        name: ansible-aws
        region: ap-south-1
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
    register: ec2_key_result

  - name: Save private key
    copy: 
      content: "{{ ec2_key_result.key.private_key }}" 
      dest: "./ansible-aws.pem" 
      mode: 0600
    when: ec2_key_result.changed

  - debug:
      var: ec2_key_result.msg